POST http://localhost:8083/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8083/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8083/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll

###
GET  http://localhost:8083/event/all

###
PUT http://localhost:8083/event/edit/299
Content-Type: application/json

{
  "eventName": "ooo",
  "description": "Edit again2",
  "dateTime": "2024-01-25T12:00:00Z",
  "capacity": 100
}

### // Creating favorite with specific eventID and UserId (objectIDs)
POST http://localhost:8083/favorites/add
Content-Type: application/json

{
  "userId": "63d29626a71c78631383d8d4",
  "eventId": "65bc5528ca64719df3347e66"
}

### // Get favorites using User's objectID
GET http://localhost:8083/favorites/user/63d29626a71c78631383d8d4

### //Delete using Favorite's objectID
DELETE http://localhost:8083/favorites/delete/65bcb0fbe2c3192bb6bba60e