POST http://localhost:8083/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8083/user/login
Content-Type: application/json 

{
    "username" : "Junior01",
    "password" : "01020304j"
}

###
GET http://localhost:8083/user/getAll
Content-Type: application/json

###

POST http://localhost:8083/user/editUser
Content-Type: application/json 

{
    "userId" : "65deb326ab5690e838eaa5d4",
    "username" : "JuniorAdmin",
    "email" : "Junior18@hotmail.com",
    "password" : "01020304j",
    "fullName" : "Jun",
    "role" : "Admin"

}

###
GET  http://localhost:8083/user/getUserById/65def11d931b1a05f0938782
Content-Type: application/json 


###
POST  http://localhost:8081/user/deleteAll

###
GET  http://localhost:8083/event/all
###
POST http://localhost:8083/event/create
Content-Type: application/json

{
  "eventName": "Eaffk ",
  "description": "Testing the event edit",
  "dateTime": "2024-01-25T12:00:00Z",
  "capacity": 100
}
###
DELETE http://localhost:8083/event/delete/134
###
PUT http://localhost:8083/event/edit/285
Content-Type: application/json

{
  "eventName": "editing once againn ",
  "description": "Testing the event edit",
  "dateTime": "2024-01-25T12:00:00Z",
  "capacity": 100
}
###
GET http://localhost:8083/event/details/285


### // Creating favorite with specific eventID and UserId (objectIDs)
POST http://localhost:8083/favorites/add
Content-Type: application/json

{
  "userId": "63d29626a71c78631383d8d4",
  "eventId": "65bc5528ca64719df3347e66"
}

### // Get favorites using User's objectID
GET http://localhost:8083/favorites/user/63d29626a71c78631383d8d4

### //Delete using Favorite's objectID
DELETE http://localhost:8083/favorites/delete/65bcb0fbe2c3192bb6bba60e

### // Creating Join with specific eventID and UserId (objectIDs)
POST http://localhost:8083/api/user/participate
Content-Type: application/json

{
  "eventId": "65bc752a1d45e2a75b08f1a4",
  "userId": "65bd15ee2205efdd8fed43b0"
  
}
###
GET http://localhost:8083/comments/event/65dd5c10dc4843cfa528aa4f
